(() => {
  const canvas=document.getElementById('game'), ctx=canvas.getContext('2d');
  ctx.imageSmoothingEnabled=true;
  const W=1280,H=720,GAME_SECONDS=45,PLAYER_X=185,BASE_SPEED=330,TOP=105,BOTTOM=655;
  const keys=new Set(); let screen='home',paused=false,musicOn=true,audioCtx=null,musicTimer=null;
  let touchActive=false,touchY=H/2,touchPointerId=null,lastSwimSound=0;
  let selectedPlayer='mermaid',selectedScene='tropical',selectedDifficulty='easy',game=null;
  const difficulties={
    easy:{name:'EASY',speed:.40,playerAccel:1350,spawnMin:2.00,spawnMax:2.90,color:'#48d66b'},
    medium:{name:'MEDIUM',speed:.95,playerAccel:1700,spawnMin:.58,spawnMax:.90,color:'#ffd748'},
    hard:{name:'HARD',speed:1.24,playerAccel:2100,spawnMin:.34,spawnMax:.56,color:'#ff6b62'}
  };

  const files={
    mermaid:'mermaid.png',scuba:'scuba.png',torpedo:'torpedo.png',mermacorn:'mermacorn.png',shark:'shark.png',crab:'crab.png',jellyfish:'jellyfish.png',octopus:'octopus.png',
    squid:'squid.png',polar_bear:'polar_bear.png',narwhal:'narwhal.png',turtle:'turtle.png',
    snowflake:'snowflake.svg',pineapple:'pineapple.svg',pearl:'pearl.svg',starfish:'starfish.svg',chest:'chest.svg',crystal:'crystal.svg',
    bg_arctic:'bg_arctic.jpg',bg_tropical:'bg_tropical.jpg',bg_coral:'bg_coral.jpg',bg_grass:'bg_grass.jpg',bg_pirate:'bg_pirate.jpg',bg_deep:'bg_deep.jpg'
  };
  const art={}; Object.entries(files).forEach(([k,f])=>{const im=new Image();im.src='assets/'+f;art[k]=im;});

  const scenes={
    arctic:{name:'ARCTIC WATERS',obstacles:['polar_bear','narwhal'],prize:'snowflake',prizeName:'ICE CRYSTAL',music:[220,277,330,440,330,277]},
    tropical:{name:'TROPICAL REEF',obstacles:['shark','crab'],prize:'pineapple',prizeName:'GOLDEN PINEAPPLE',music:[330,392,523,440,392,349,523,659]},
    coral:{name:'CORAL KINGDOM',obstacles:['jellyfish','octopus'],prize:'pearl',prizeName:'PEARL IN CLAM',music:[294,370,440,554,494,440]},
    grass:{name:'SEAGRASS MEADOW',obstacles:['squid','turtle'],prize:'starfish',prizeName:'GOLDEN STARFISH',music:[262,330,392,330,294,349]},
    pirate:{name:'PIRATE COVE',obstacles:['shark','octopus'],prize:'chest',prizeName:'PIRATE CHEST',music:[196,247,294,330,294,247,220]},
    deep:{name:'DEEP BLUE',obstacles:['squid','jellyfish'],prize:'crystal',prizeName:'BLUE GEM',music:[147,196,220,185,165,220]}
  };
  const order=['arctic','tropical','coral','grass','pirate','deep'];

  function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();}
  function tone(freq,d=.08,type='triangle',vol=.025,delay=0){if(!musicOn)return;ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;const t=audioCtx.currentTime+delay;g.gain.setValueAtTime(Math.max(.001,vol),t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+d+.02);}
  const sfx={select(){tone(620,.045,'sine',.035);tone(820,.05,'sine',.025,.045)},point(){tone(880,.07,'triangle',.05);tone(1175,.09,'triangle',.04,.055)},start(){tone(330,.07,'triangle',.035);tone(440,.07,'triangle',.035,.07);tone(660,.10,'triangle',.04,.14)},swim(){tone(520+Math.random()*120,.035,'sine',.012);tone(760+Math.random()*120,.025,'sine',.008,.025)},treasure(){tone(740,.10,'sine',.035);tone(990,.12,'sine',.03,.08);tone(1320,.15,'sine',.025,.16)},win(){[523,659,784,1047,1319].forEach((n,i)=>tone(n,.18,'triangle',.05,i*.09))}};
  function startMusic(){stopMusic();if(!musicOn)return;ensureAudio();const seq=scenes[selectedScene].music;let i=0;musicTimer=setInterval(()=>tone(seq[i++%seq.length],.16,'triangle',.018),240);}
  function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null;}}
  function toggleSound(){musicOn=!musicOn;if(musicOn){ensureAudio();startMusic();sfx.select();}else stopMusic();}

  function txt(t,x,y,size=24,align='left',fill='#fff',stroke='#06315d'){ctx.save();ctx.font=`800 ${size}px system-ui,Arial`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.lineWidth=Math.max(3,size/8);ctx.strokeStyle=stroke;ctx.strokeText(t,x,y);ctx.fillStyle=fill;ctx.fillText(t,x,y);ctx.restore();}
  function txtSpaced(t,x,y,size=24,spacing=1.5,fill='#fff',stroke='#06315d',weight=600){ctx.save();ctx.font=`${weight} ${size}px system-ui,Arial`;ctx.textBaseline='middle';ctx.lineWidth=Math.max(1.5,size/12);const chars=[...t], widths=chars.map(c=>ctx.measureText(c).width);const total=widths.reduce((a,b)=>a+b,0)+spacing*Math.max(0,chars.length-1);let px=x-total/2;ctx.strokeStyle=stroke;ctx.fillStyle=fill;for(let i=0;i<chars.length;i++){ctx.strokeText(chars[i],px,y);ctx.fillText(chars[i],px,y);px+=widths[i]+spacing;}ctx.restore();}
  function box(x,y,w,h,fill='#063b70df',stroke='#54d7ff',lw=3,r=18){ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke();ctx.restore();}
  function sprite(name,x,y,w,h,bob=0){const im=art[name];if(!im?.complete||!im.naturalWidth)return;const a=im.naturalWidth/im.naturalHeight;let dw=w,dh=h;if(dw/dh>a)dw=dh*a;else dh=dw/a;ctx.drawImage(im,x-dw/2,y+bob-dh/2,dw,dh);}
  function bg(id,scroll=0){const im=art['bg_'+id];if(!im?.complete||!im.naturalWidth){ctx.fillStyle='#087bc0';ctx.fillRect(0,0,W,H);return;}const maxPan=Math.max(0,im.naturalWidth-W);const travel=Math.min(maxPan-20,scroll*.040);ctx.drawImage(im,travel,0,W,H,0,0,W,H);}

  const playerBoxes=[{id:'mermaid',x:35,y:100,w:285,h:155},{id:'scuba',x:343,y:100,w:285,h:155},{id:'torpedo',x:651,y:100,w:285,h:155},{id:'mermacorn',x:959,y:100,w:285,h:155}];
  const sceneBoxes=order.map((id,i)=>({id,x:18+i*209,y:318,w:194,h:210}));
  const difficultyBoxes=[{id:'easy',x:360,y:582,w:170,h:42},{id:'medium',x:555,y:582,w:170,h:42},{id:'hard',x:750,y:582,w:170,h:42}];
  const playBox={x:500,y:640,w:280,h:54};
  const homeBox={x:18,y:H-66,w:138,h:46};
  const soundGameBox={x:168,y:H-66,w:170,h:46};
  const soundHomeBox={x:1080,y:640,w:180,h:54};
  const againBox={x:420,y:625,w:210,h:52},endHomeBox={x:650,y:625,w:210,h:52};

  function sceneCard(id,b){const s=scenes[id],sel=id===selectedScene;box(b.x,b.y,b.w,b.h,'#06335fe9',sel?'#ffe34f':'#4ed6ff',sel?6:3,16);txt(s.name,b.x+b.w/2,b.y+21,15,'center');const im=art['bg_'+id];if(im?.complete){ctx.save();ctx.beginPath();ctx.roundRect(b.x+8,b.y+40,b.w-16,92,10);ctx.clip();ctx.drawImage(im,b.x+8,b.y+40,b.w-16,92);ctx.restore();}txt('COLLECTIBLES',b.x+b.w/2,b.y+136,11,'center','#65eaff');sprite(s.obstacles[0],b.x+55,b.y+166,60,48);sprite(s.obstacles[1],b.x+139,b.y+166,60,48);txt('PRIZE',b.x+b.w/2,b.y+190,11,'center','#ffd748');sprite(s.prize,b.x+b.w/2,b.y+208,36,36);}

  function drawHome(){bg('tropical',performance.now()/30);ctx.fillStyle='#01284e80';ctx.fillRect(0,0,W,H);txt('SPLASHY SEAS',W/2,48,52,'center','#ff77b4','#07315a');txt('1. CHOOSE YOUR SWIMMER',W/2,82,19,'center','#ffd748');for(const b of playerBoxes){const sel=b.id===selectedPlayer;const labels={mermaid:'MERMAID',scuba:'SCUBA GUY',torpedo:'FRIENDLY TORPEDO',mermacorn:'MERMACORN'};const widths={mermaid:150,scuba:148,torpedo:190,mermacorn:190};box(b.x,b.y,b.w,b.h,'#073b6ded',sel?'#ffe34f':'#56d9ff',sel?6:3,20);sprite(b.id,b.x+b.w/2,b.y+65,widths[b.id],96,Math.sin(performance.now()/300)*2);txt(labels[b.id],b.x+b.w/2,b.y+130,b.id==='torpedo'?15:17,'center',sel?'#ffe34f':'#fff');}txt('2. CHOOSE YOUR SCENE',W/2,292,20,'center','#ffd748');sceneBoxes.forEach(b=>sceneCard(b.id,b));txt('3. CHOOSE DIFFICULTY',W/2,558,17,'center','#ffd748');for(const b of difficultyBoxes){const d=difficulties[b.id],sel=b.id===selectedDifficulty;box(b.x,b.y,b.w,b.h,sel?d.color:'#063b70e8',sel?'#ffffff':'#54d7ff',sel?5:3,14);txtSpaced(d.name,b.x+b.w/2,b.y+b.h/2,17,2.4,sel?'#06264a':'#fff','#06315d',550);}box(playBox.x,playBox.y,playBox.w,playBox.h,'#26ae4d','#e2ffcf',4,18);txt('PLAY',W/2,667,27,'center');box(soundHomeBox.x,soundHomeBox.y,soundHomeBox.w,soundHomeBox.h,'#063b70e8','#54d7ff',3,16);txt(musicOn?'SOUND ON':'SOUND OFF',soundHomeBox.x+soundHomeBox.w/2,soundHomeBox.y+soundHomeBox.h/2,16,'center',musicOn?'#9dffb0':'#ffb0b0');}

  const dims={shark:[135,76],crab:[81,68],jellyfish:[72,86],octopus:[90,81],squid:[108,72],polar_bear:[117,86],narwhal:[130,72],turtle:[108,72]};
  function spawnObstacle(){const a=scenes[selectedScene].obstacles,type=a[Math.random()<.5?0:1];const zones=[{min:TOP+18,max:TOP+90,weight:1.0},{min:TOP+95,max:TOP+205,weight:1.25},{min:TOP+210,max:BOTTOM-210,weight:1.45},{min:BOTTOM-205,max:BOTTOM-95,weight:1.25},{min:BOTTOM-90,max:BOTTOM-18,weight:1.0}];const total=zones.reduce((sum,z)=>sum+z.weight,0);let pick=Math.random()*total,zone=zones[2];for(const z of zones){pick-=z.weight;if(pick<=0){zone=z;break;}}let y;const minGap=105;for(let tries=0;tries<14;tries++){const candidate=zone.min+Math.random()*(zone.max-zone.min);if(game.lastSpawnY===null||Math.abs(candidate-game.lastSpawnY)>=minGap){y=candidate;break;}if(tries>7&&Math.random()<0.22){y=candidate;break;}}if(y===undefined){const shuffled=[...zones].sort(()=>Math.random()-.5);for(const z of shuffled){const candidate=z.min+Math.random()*(z.max-z.min);if(game.lastSpawnY===null||Math.abs(candidate-game.lastSpawnY)>=80){y=candidate;break;}}if(y===undefined)y=TOP+40+Math.random()*(BOTTOM-TOP-80);}game.lastSpawnY=y;game.obstacles.push({type,x:W+110,y,phase:Math.random()*6.28,collected:false});}

  function newGame(){const d=difficulties[selectedDifficulty];game={player:{y:H/2,vy:0,t:0},score:0,elapsed:0,spawn:d.spawnMin,distance:0,obstacles:[],prizeX:null,lastSpawnY:null,prizeSoundPlayed:false};paused=false;}
  function update(dt){if(paused)return;const d=difficulties[selectedDifficulty],speed=BASE_SPEED*d.speed;const p=game.player,up=keys.has('ArrowUp')||keys.has('KeyW'),down=keys.has('ArrowDown')||keys.has('KeyS');if(touchActive){const target=Math.max(TOP+42,Math.min(BOTTOM-42,touchY));const maxTouchSpeed=560+250*d.speed,delta=target-p.y,step=Math.sign(delta)*Math.min(Math.abs(delta),maxTouchSpeed*dt);p.y+=step;p.vy=0;if(Math.abs(delta)>10&&performance.now()-lastSwimSound>280){sfx.swim();lastSwimSound=performance.now();}}else{p.vy+=(down-up)*d.playerAccel*dt;p.vy*=Math.pow(.0018,dt);p.y=Math.max(TOP+42,Math.min(BOTTOM-42,p.y+p.vy*dt));if((up||down)&&performance.now()-lastSwimSound>320){sfx.swim();lastSwimSound=performance.now();}}p.t+=dt;game.elapsed+=dt;game.distance+=speed*dt;game.spawn-=dt;if(game.spawn<=0&&game.elapsed<GAME_SECONDS){spawnObstacle();game.spawn=d.spawnMin+Math.random()*(d.spawnMax-d.spawnMin);}if(game.elapsed>=GAME_SECONDS&&game.prizeX===null){game.prizeX=W+120;if(!game.prizeSoundPlayed){game.prizeSoundPlayed=true;sfx.treasure();}}if(game.prizeX!==null)game.prizeX-=BASE_SPEED*.72*dt;for(const o of game.obstacles){o.x-=speed*dt;o.phase+=dt;o.y+=Math.sin(o.phase*2.5)*16*dt;const [ow,oh]=dims[o.type],dx=o.x-PLAYER_X,dy=o.y-p.y;if(!o.collected&&Math.abs(dx)<ow*.36+31&&Math.abs(dy)<oh*.35+25){o.collected=true;game.score++;sfx.point();}}game.obstacles=game.obstacles.filter(o=>!o.collected&&o.x>-150);if(game.prizeX!==null){if(Math.abs(game.prizeX-PLAYER_X)<62&&Math.abs(360-p.y)<62){screen='win';stopMusic();sfx.win();}if(game.prizeX<-90)game.prizeX=W+100;}}

  function drawHUD(){box(15,12,300,62,'#063b70dd','#53d7ff',3,16);txt('COLLECT THEM!',165,30,15,'center','#9dffb0');txt('Touch the animals',165,53,15,'center','#ffffff');box(W-300,12,285,62,'#063b70dd','#53d7ff',3,16);txt('COLLECTED',W-155,28,13,'center','#d9f7ff');txt(String(game.score).padStart(3,'0'),W-155,53,29,'center','#ffd748');txt(`TIME ${String(Math.max(0,Math.ceil(GAME_SECONDS-game.elapsed))).padStart(2,'0')}`,W/2,34,19,'center');txt(difficulties[selectedDifficulty].name,W/2,61,12,'center',difficulties[selectedDifficulty].color);}
  function drawGame(){bg(selectedScene,game.distance);drawHUD();txt(scenes[selectedScene].name,W/2,80,21,'center');for(const o of game.obstacles){const [ww,hh]=dims[o.type];sprite(o.type,o.x,o.y,ww,hh,Math.sin(o.phase*6)*2);}if(game.prizeX!==null){ctx.save();ctx.globalAlpha=.18;ctx.fillStyle='#fff45e';ctx.beginPath();ctx.arc(game.prizeX,360,70+Math.sin(game.elapsed*8)*5,0,Math.PI*2);ctx.fill();ctx.restore();sprite(scenes[selectedScene].prize,game.prizeX,360,92,110,Math.sin(game.elapsed*6)*3);txt('SWIM INTO THE PRIZE!',game.prizeX,435,14,'center','#ffe13f');}sprite(selectedPlayer,PLAYER_X,game.player.y,selectedPlayer==='mermaid'?189:184,124,Math.sin(game.player.t*7)*2);box(homeBox.x,homeBox.y,homeBox.w,homeBox.h,'#063b70dd','#54d7ff',3,14);txt('HOME',homeBox.x+homeBox.w/2,homeBox.y+homeBox.h/2,16,'center');box(soundGameBox.x,soundGameBox.y,soundGameBox.w,soundGameBox.h,'#063b70dd','#54d7ff',3,14);txt(musicOn?'SOUND ON':'SOUND OFF',soundGameBox.x+soundGameBox.w/2,soundGameBox.y+soundGameBox.h/2,14,'center',musicOn?'#9dffb0':'#ffb0b0');if(paused){ctx.fillStyle='#012649cc';ctx.fillRect(0,0,W,H);txt('PAUSED',W/2,H/2-25,50,'center','#ffd748');txt('P = RESUME   •   ESC/HOME = HOME',W/2,H/2+35,19,'center');}}
  function drawEnd(){bg(selectedScene,game?.distance||0);ctx.fillStyle='#012649c9';ctx.fillRect(0,0,W,H);txt('GREAT COLLECTING!',W/2,145,56,'center','#ffd748');sprite(selectedPlayer,W/2-120,320,190,128);sprite(scenes[selectedScene].prize,W/2+120,315,120,140);txt(`COLLECTED ${game.score}`,W/2,465,28,'center');txt(`${scenes[selectedScene].name} • ${scenes[selectedScene].prizeName}`,W/2,510,18,'center','#d9f7ff');box(againBox.x,againBox.y,againBox.w,againBox.h,'#26ae4d','#e2ffcf',4,16);txt('PLAY AGAIN',againBox.x+againBox.w/2,againBox.y+againBox.h/2,18,'center');box(endHomeBox.x,endHomeBox.y,endHomeBox.w,endHomeBox.h,'#063b70dd','#54d7ff',3,16);txt('HOME',endHomeBox.x+endHomeBox.w/2,endHomeBox.y+endHomeBox.h/2,18,'center');}

  function begin(){ensureAudio();newGame();screen='game';touchActive=false;startMusic();sfx.start();}
  function home(){screen='home';paused=false;touchActive=false;stopMusic();if(musicOn)startMusic();}
  function inside(x,y,b){return x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h;}
  function clickHome(x,y){for(const b of playerBoxes)if(inside(x,y,b)){selectedPlayer=b.id;sfx.select();return;}for(const b of sceneBoxes)if(inside(x,y,b)){selectedScene=b.id;startMusic();sfx.select();return;}for(const b of difficultyBoxes)if(inside(x,y,b)){selectedDifficulty=b.id;sfx.select();return;}if(inside(x,y,playBox)){begin();return;}if(inside(x,y,soundHomeBox)){toggleSound();return;}}
  function canvasPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
  canvas.addEventListener('pointerdown',e=>{ensureAudio();if(musicOn&&!musicTimer&&screen==='home')startMusic();const {x,y}=canvasPoint(e);if(screen==='home'){clickHome(x,y);return;}if(screen==='game'){if(inside(x,y,homeBox)){home();return;}if(inside(x,y,soundGameBox)){toggleSound();return;}touchActive=true;touchY=y;touchPointerId=e.pointerId;canvas.setPointerCapture?.(e.pointerId);return;}if(screen==='win'){if(inside(x,y,againBox)){begin();return;}if(inside(x,y,endHomeBox)){home();return;}}});
  canvas.addEventListener('pointermove',e=>{if(screen==='game'&&touchActive&&e.pointerId===touchPointerId){touchY=canvasPoint(e).y;e.preventDefault();}});
  const endTouch=e=>{if(e.pointerId===touchPointerId){touchActive=false;touchPointerId=null;}};canvas.addEventListener('pointerup',endTouch);canvas.addEventListener('pointercancel',endTouch);
  addEventListener('keydown',e=>{keys.add(e.code);if(['ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&screen!=='home'){home();return;}if(e.code==='KeyP'&&screen==='game')paused=!paused;if(e.code==='KeyM')toggleSound();if(screen==='win'&&(e.code==='Enter'||e.code==='Space'))begin();if(screen==='home'&&(e.code==='Enter'||e.code==='Space'))begin();});
  addEventListener('keyup',e=>keys.delete(e.code));
  let last=performance.now();function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;if(screen==='game')update(dt);screen==='home'?drawHome():screen==='game'?drawGame():drawEnd();requestAnimationFrame(loop);}requestAnimationFrame(loop);
})();
